apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DATABASE_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DATABASE_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: DATABASE_NAME
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /mnt/data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort  # Alterado de ClusterIP para NodePort, com isso é possível acessar o banco de dados externamente
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006  # Porta acessível no host
  selector:
    app: mysql