CREATE TABLE IF NOT EXISTS pedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT,
  status VARCHAR(15) NOT NULL,
  status_pagamento VARCHAR(15) NOT NULL,
  pedido_data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);